### PR TITLE
Apply output filters in scripts with an src only (#6)

### PR DESCRIPTION
**Pull request by nlemoine**
Not a brilliant solution but will do the job.

### CODE REVIEW

**Comment by Chrico** [comment]
Howdy @nlemoine ,

thanks for you feedback and pull request. 

This might can work, but filters are flexible in use. You could even add a filter which add's additonal attributes to the `script`-Tag. What could be possible is to enhance the `appendInlineScript`-method by removing the `AsyncScriptOutputFilter` and `DeferScriptOutputFilter` if present.

**Comment by nlemoine** [comment]
I think this won't work. First, output filters are applied with the `script_loader_tag` hook which contains everything: 

```html
/* before */
<script>var foo = 'bar';</script>
/* handle */
<script src="foo.js"></script>
/* after */
<script>var bar = 'foo';</script>
```

Therefore it's not possible to distinguish on which `script` tag the filters should be applied: 
https://github.com/WordPress/WordPress/blob/master/wp-includes/class.wp-scripts.php#L387-L400

I'm also using the array loader and the `appendInlineScript` is never called.

**Comment by nlemoine** [comment]
Here's what my script looks like:

```php
    [
        'handle'   => 'script-id',
        'url'      => 'https://url.com/foo.js',
        'location' => Asset::FRONTEND,
        'type'     => Script::class,
        'filters'  => [
            DeferScriptOutputFilter::class,
        ],
        'inline' => [
            'after' => [
                "document.addEventListener('DOMContentLoaded', function(){foo.init()});",
            ],
        ],
    ],
```

**Comment by Chrico** [comment]
Thanks for your feedback and more context to what you want achieve. :) I unterstand now, that you only want to have the `script` which has a `src` to be executed defered, while the inline scripts shouldn't be defered. Sames goes for async.

Is there might be a chance where it makes sense to have the script with src and the inline scripts to be async/defered? At least async for inline scripts should have an impact of rendering. Overall i just want to aovid breaking changes with your Pull Request. :-) 

Until we decided, merged and created a release, it's might be helpful for you to add an own custom filter:

```php
<?php

    [
        'handle'   => 'script-id',
        'url'      => 'https://url.com/foo.js',
        'location' => Asset::FRONTEND,
        'type'     => Script::class,
        'filters'  => [
            function( string $html, Asset $asset ): string
            {

                return str_replace('<script src=', '<script defer src=', $html);
            }
        ],
        'inline' => [
            'after' => [
                "document.addEventListener('DOMContentLoaded', function(){foo.init()});",
            ],
        ],
    ],
```

**Comment by nlemoine** [comment]
Thanks for your feedback and your workaround! :)

I don't think `defer` and `async` attributes have any effect on inline scripts: https://stackoverflow.com/questions/41394983/how-to-defer-inline-javascript

> Overall i just want to aovid breaking changes with your Pull Request. :-)

I totally understand. I'm currently using a custom branch with my fix and it works fine for now. Find my insights below.

---

I had a deeper look to check what could go wrong with that fix. As WordPress generates the `script`, [we are almost certain](https://github.com/WordPress/WordPress/blob/master/wp-includes/class.wp-scripts.php#L388) that we will always have those exact characters: `<script src=`. 

But in some situations, this can fail.

### Theme does not support `html5`

A placeholder is placed right after `<script%s` and [can output a ` type="text/javascript"`](https://github.com/WordPress/WordPress/blob/master/wp-includes/class.wp-scripts.php#L152-L158) (`type_attr`). However, this can probably be handled. 

### Some inline JS contains `<script src=`

The fix will then mess up the inline code.

--- 

Fixing this in a reliable way would require to parse HTML and only add the `async`/`defer` attribute to the tags containing an `src` attribute. But this would make the script heavier. One solution could be to add the handle URL inside the `str_replace` to make the replacement really reliable.

Let me know what you think.

**Comment by nlemoine** [comment]
Hi, 

I just started working on this issue again.

Here's a couple of solutions to address it and better target the right `script`

### Use the asset URL (1)

```php
str_replace("src='{$asset->url()}", "defer src='{$asset->url()}", $html);
```
👍 Ensure the right `script` tag is replaced
👍 Will handle `version` (`?ver=1.2.3`)
👎 Although it's very unlikely, might interfere with inline scripts if some of them contain the same string

### Use the asset URL (2)

```php
$typeAttr = function_exists( 'is_admin' ) && ! is_admin() && function_exists( 'current_theme_supports' ) && ! current_theme_supports( 'html5', 'script' ) ? " type='text/javascript'" : '';
str_replace("<script{$typeAttr} src='{$asset->url()}", "<script{$typeAttr} defer src='{$asset->url()}", $html);
```
👍 Ensure the right `script` tag is replaced
👍 Will handle `version` (`?ver=1.2.3`)
👎 Although it's very very very unlikely, might interfere with inline scripts if some of them contain the same string
👎 Might change if WordPress changes script rendering

### Use the asset ID

```php
str_replace("id='{$asset->handle()}-js'", "defer id='{$asset->handle()}-js'", $html);
```
Same pros/cons.

### Use a regex

Replace with regex using the closest pattern available. Something like: 
```php
$typeAttr = function_exists( 'is_admin' ) && ! is_admin() && function_exists( 'current_theme_supports' ) && ! current_theme_supports( 'html5', 'script' ) ? " type='text/javascript'" : '';
$pattern = "/<script {$typeAttr} src='{$asset->url()}?(\?ver=(.*))' id='{$asset->handle()}-js'><\/script>/m";
``` 

👍  This would probably be the most reliable solution (excluding DOM parsing).
👎 Slower


Let me know what you think, or if you're still interested in finding a workaround for this.

**Comment by nlemoine** [comment]
Hi, 

I just started working on this issue again.

Here's a couple of solutions to address it and better target the right `script`

### Use the asset URL (1)

```php
str_replace("src='{$asset->url()}", "defer src='{$asset->url()}", $html);
```
👍 Ensure the right `script` tag is replaced
👍 Will handle `version` (`?ver=1.2.3`)
👎 Although it's very unlikely, might interfere with inline scripts if some of them contain the same string

### Use the asset URL (2)

```php
$typeAttr = function_exists( 'is_admin' ) && ! is_admin() && function_exists( 'current_theme_supports' ) && ! current_theme_supports( 'html5', 'script' ) ? " type='text/javascript'" : '';
str_replace("<script{$typeAttr} src='{$asset->url()}", "<script{$typeAttr} defer src='{$asset->url()}", $html);
```
👍 Ensure the right `script` tag is replaced
👍 Will handle `version` (`?ver=1.2.3`)
👎 Although it's very very very unlikely, might interfere with inline scripts if some of them contain the same string
👎 Might change if WordPress changes script rendering

### Use the asset ID

```php
str_replace("id='{$asset->handle()}-js'", "defer id='{$asset->handle()}-js'", $html);
```
Same pros/cons.

### Use a regex

Replace with regex using the closest pattern available. Something like: 
```php
$typeAttr = function_exists( 'is_admin' ) && ! is_admin() && function_exists( 'current_theme_supports' ) && ! current_theme_supports( 'html5', 'script' ) ? " type='text/javascript'" : '';
$pattern = "/<script {$typeAttr} src='{$asset->url()}?(\?ver=(.*))' id='{$asset->handle()}-js'><\/script>/m";
``` 

👍  This would probably be the most reliable solution (excluding DOM parsing).
👎 Slower


Let me know what you think, or if you're still interested in finding a workaround for this.

**Pull request closed without merging**
